# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java 18.0.1.1
        run: |
          wget https://download.oracle.com/java/18/archive/jdk-18.0.1.1_linux-x64_bin.tar.gz
          tar -xvzf jdk-18.0.1.1_linux-x64_bin.tar.gz
          sudo mv jdk-18.0.1.1 /opt/jdk
          echo "export JAVA_HOME=/opt/jdk" >> $GITHUB_ENV
          echo "export PATH=/opt/jdk/bin:$PATH" >> $GITHUB_ENV
          
      - name: Check Java version
        run: java -version

      - name: Install Maven 3.9.9
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
          tar -xvzf apache-maven-3.9.9-bin.tar.gz
          sudo mv apache-maven-3.9.9 /opt/maven
          echo "export PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV
      

      - name: Check Maven version
        run: mvn -version

      - name: Build with Maven
        run: mvn package

      - name: Maven Tests
        run: mvn test
